version = 0.1
[default.deploy.parameters]
stack_name = "api-gateway-usage-plan-solution"
resolve_s3 = true
s3_prefix = "api-gateway-usage-plan-solution"
region = "us-east-2"
profile = "AdministratorAccess-117763952852"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
